# This workflow will run daily at 06:45.
# It will install Python dependencies and run tests with a variety of Python versions.

name: Unit test smoke test

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10']
        notebook-dir: ['creation'] #'core', 'creation', 'estimation', 'evaluation', 'goldenspike']

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        sudo apt-get update
        python -m pip install --upgrade pip
        pip install wheel numpy
        pip install .
        pip install .[dev]
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run unit tests with pytest
      run: |
        python -m pytest tests
#    - name: Set up fsps
#      run: |
#        git clone --recursive https://github.com/dfm/python-fsps.git
#        cd python-fsps
#        python -m pip install .
#        export SPS_HOME=$(pwd)/src/fsps/libfsps
    - name: More fsps set up
      uses: jannekem/run-python-script-action@v1
      with:
        script: |
          import os
          import subprocess
          if "SPS_HOME" not in os.environ:
            os.environ["SPS_HOME"] = "/opt/hostedtoolcache/Python/fsps"
            subprocess.run(["git", "clone", "https://github.com/cconroy20/fsps.git",
                            "/opt/hostedtoolcache/Python/fsps"], capture_output=True)
    - run: echo "$SPS_HOME"
    - run: echo "SPS_HOME=/opt/hostedtoolcache/Python/fsps" >> $GITHUB_ENV
    - run: echo ${{env.SPS_HOME}}
    - name: Run notebooks
      run: |
        rail render-nb examples/${{ matrix.notebook-dir }}_examples/*.ipynb
